---
# tasks file for nginx_proxy
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
  when: ansible_os_family == 'Debian'

- name: Create proxy configuration
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
