---
linux: # Группа хостов
  children: # Подгруппы хостов
    nginx: # Имя подгруппы
      hosts: # Узлы группы
        vm_1:
          ansible_host: 158.160.42.118
        vm_2:
          ansible_host: 89.169.139.63
        vm_3:
          ansible_host: 51.250.6.167
  vars: # Переменные для всей группы linux
    ansible_user: "vintus"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_connection: ssh
    ansible_become: true
    ansible_become_method: sudo
    ansible_host_key_checking: False
